
# 打分标准
std = {
    "_0pts": 0,
    "_1pts": 1,
    "_2pts": 2,
    "_3pts": 3,
    "o_reb": 1.8,
    "d_reb": 1.2,
    "ast": 1.5,
    "to": -1.5,
    "fol": -1,
    "t": -5,
    "stl": 2.5,
    "blk": 2.5,
    "mk_o_fol": 1.5
}

# 范句与得分字典
point_dict = {
    '<player_name>助攻<player_name>，<location>抛投命中': [std['ast'], std['_2pts']],
    '<player_name>接到<player_name>的助攻转身勾手，打板入网': [std['_2pts'], std['ast']],
    '<player_name>罚球命中': [std['_1pts']],
    '<player_name>抢到前场篮板，补篮被<player_name>盖掉': [std['o_reb'], std['blk']],
    '<player_name>失误，3秒违例': [std['to']],
    '<player_name>上篮得分': [std['_2pts']],
    '<player_name>后仰打板跳投不中': [std['_0pts']],
    '<player_name>后撤步跳投<location>命中': [std['_2pts']],
    '<player_name>接到<player_name>的助攻运球突破，勾手打板入网': [std['_2pts'], std['ast']],
    '<player_name><location>急停跳投三分打板入网': [std['_3pts']],
    '<player_name>助攻<player_name>，<player_name>空中接力上篮得分': [std['ast'], std['_0pts'], std['_2pts']],
    '<player_name>罚球命中 (两罚第一罚)': [std['_1pts']],
    '快攻无防守犯规罚球，<player_name>罚球命中 (两罚第二罚)': [std['_1pts']],
    '<player_name><location>后撤步跳投，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>后仰跳投命中': [std['_2pts']],
    '<player_name>急停跳投不中': [std['_0pts']],
    '<player_name>挑篮不中': [std['_0pts']],
    '<player_name>行进间挑篮不中': [std['_0pts']],
    '<player_name>勾手擦板入网': [std['_2pts']],
    '<player_name><location>转身跳投，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>转身勾手命中': [std['_2pts']],
    '<player_name><location>急停跳投命中': [std['_2pts']],
    '<player_name>跨步扣篮不中': [std['_0pts']],
    '<player_name>脚踢球违例': [std['fol']],
    '恶意犯规罚球，<player_name>罚球命中 (两罚第一罚)': [std['_1pts']],
    '<player_name>打板投篮，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>二次技术犯规，被驱逐出场': [std['t']],
    '<player_name>抢到前场篮板，补篮命中': [std['o_reb'] + std['_2pts']],
    '<player_name>反身扣篮得分': [std['_2pts']],
    '<player_name>罚球命中 (三罚第三罚)': [std['_1pts']],
    '<player_name>加罚不中': [std['_0pts']],
    '<player_name>助攻<player_name>跳投命中': [std['ast'], std['_2pts']],
    '<player_name>失误，5秒违例': [std['to']],
    '<player_name>进攻犯规 (<player_name>造成了犯规)': [std['fol'], std['mk_o_fol']],
    '<player_name><location>后撤步跳投不中': [std['_0pts']],
    '<player_name>助攻<player_name>，<location>急停跳投三分入网': [std['ast'], std['_3pts']],
    '<player_name>犯规 (<player_name>造成了犯规)，<player_name>已经6次犯规': [std['fol'], std['_0pts'], std['_0pts']],
    '<player_name>助攻<player_name>，后撤步跳投命中': [std['ast'], std['_2pts']],
    '<player_name>接到<player_name>的助攻，<location>跳投三分入网': [std['_3pts'], std['ast']],
    '<player_name>空中接力扣篮不中': [std['_0pts']],
    '<player_name>反身扣篮，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>接到<player_name>的助攻，跨步上篮得分': [std['_2pts'], std['ast']],
    '<player_name>助攻<player_name>，后撤步跳投<location>三分入网': [std['ast'], std['_3pts']],
    '<player_name><location>抛投不中': [std['_0pts']],
    '<player_name><location>打板入网': [std['_2pts']],
    '<player_name>灌篮扣飞': [std['_0pts']],
    '<player_name>后撤步跳投<location>三分入网': [std['_3pts']],
    '<player_name><location>转身后仰打板跳投，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>接到<player_name>的助攻，低手上篮得分': [std['_2pts'], std['ast']],
    '<player_name>犯规 (<player_name>造成了犯规)，<player_name>已经4次犯规': [std['fol'], std['_0pts'], std['_0pts']],
    '<player_name>助攻<player_name>反身扣篮得分': [std['ast'], std['_2pts']],
    '<player_name>被裁判吹了个悬挂篮筐的技术犯规': [std['t']],
    '<player_name><location>三分打板入网': [std['_3pts']],
    '<player_name>拿到后场篮板': [std['d_reb']],
    '<player_name>挑篮，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>接到<player_name>的助攻，带球突破后挑篮命中': [std['_2pts'], std['ast']],
    '<player_name>接到<player_name>的助攻，急停跳投打板入网': [std['_2pts'], std['ast']],
    '<player_name><location>急停跳投三分入网': [std['_3pts']],
    '<player_name>后仰跳投打板入网': [std['_2pts']],
    '<player_name>接到<player_name>的助攻，<location>转身勾手命中': [std['_2pts'], std['ast']],
    '<player_name>跳投命中': [std['_2pts']],
    '<player_name>转身跳投不中': [std['_0pts']],
    '<player_name>转身勾手，打板入网': [std['_2pts']],
    '<player_name>犯规 (<player_name>造成了犯规)，<player_name>已经5次犯规': [std['fol'], std['_0pts'], std['_0pts']],
    '<player_name><location>三分后撤步跳投不中': [std['_0pts']],
    '<player_name>带球突破灌篮，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>低手上篮得分': [std['_2pts']],
    '<player_name>失误，运球出界': [std['to']],
    '<player_name>带球突破擦板勾手投篮不中': [std['_0pts']],
    '<player_name>带球上篮得分': [std['_2pts']],
    '技术犯规罚球，<player_name>罚球命中': [std['_1pts']],
    '<player_name>运球突破，打板入网': [std['_2pts']],
    '<player_name>打板投篮不中': [std['_0pts']],
    '<player_name>勾手不中': [std['_0pts']],
    '<player_name>犯规': [std['fol']],
    '<player_name><location>跳投不中': [std['_0pts']],
    '<player_name><location>后仰跳投不中': [std['_0pts']],
    '<team_name>队失误，5秒违例': [std['to']],
    '<player_name>急停跳投命中': [std['_2pts']],
    '<player_name><location>后仰跳投，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>带球突破灌篮不中': [std['_2pts']],
    '<player_name>运球翻腕失误': [std['fol']],
    '<player_name><location>转身勾手，打板入网': [std['_2pts']],
    '<player_name>带球突破挑篮不中': [std['_0pts']],
    '<player_name>接到<player_name>的助攻<location>转身勾手，打板入网': [std['_2pts'], std['ast']],
    '快攻无防守犯规罚球，<player_name>罚球不中 (两罚第一罚)': [std['_1pts']],
    '<player_name>上篮，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>接到<player_name>的助攻，转身跳投打板入网': [std['_2pts'], std['ast']],
    '<player_name>罚球不中': [std['_0pts']],
    '<player_name>罚球不中 (两罚第一罚)': [std['_0pts']],
    '<player_name><location>跳投三分入网': [std['_3pts']],
    '恶意犯规罚球，<player_name>罚球不中 (两罚第二罚)': [std['_0pts']],
    '<player_name>助攻<player_name>，<location>急停跳投命中': [std['ast'], std['_2pts']],
    '<player_name>抛投不中': [std['_0pts']],
    '<player_name><location>跳投命中': [std['_2pts']],
    '<player_name>突破反手上篮不中': [std['_0pts']],
    '<player_name>转身后仰打板跳投不中': [std['_0pts']],
    '<player_name>传球失误，被<player_name>断下': [std['to'], std['stl']],
    '<player_name>助攻<player_name><location>跳投命中': [std['ast'], std['_2pts']],
    '<player_name><location>带球突破擦板勾手投篮不中': [std['_0pts']],
    '<player_name><location>勾手命中': [std['_2pts']],
    '<player_name>助攻<player_name>空中接力灌篮得分': [std['ast'], std['_2pts']],
    '<player_name>在对方投篮时犯规 (<player_name>造成了犯规)': [std['_0pts'], std['_0pts']],
    '<player_name><location>三分急停跳投，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>转身勾手，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>跳投不中': [std['_0pts']],
    '<player_name>跨步上篮得分': [std['_2pts']],
    '<team_name>换人，<player_name>换下了<player_name>': [std['_0pts'], std['_0pts']],
    '<player_name>接到<player_name>的助攻，后仰跳投命中': [std['_2pts'], std['ast']],
    '<player_name><location>急停跳投，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>运球突破勾手投篮得分': [std['_2pts']],
    '<player_name>失误 (带球撞人)': [std['to']],
    '<player_name>投篮得分': [std['_2pts']],
    '<player_name>快攻无防守犯规 (<player_name>造成了犯规)': [std['fol'], std['_0pts']],
    '<player_name><location>抛投命中': [std['_2pts']],
    '<player_name>反身扣篮不中': [std['_0pts']],
    '<player_name>转身跳投打板入网': [std['_2pts']],
    '<player_name>接到<player_name>的助攻，跨步扣篮得分': [std['_2pts'], std['ast']],
    '<player_name>接到<player_name>的助攻，<location>打板入网': [std['_2pts'], std['ast']],
    '<player_name>跨步反手上篮，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>走步': [std['to']],
    '<player_name>跨步上篮不中': [std['_0pts']],
    '<player_name>助攻<player_name>上篮得分': [std['ast'], std['_2pts']],
    '<player_name>跨步扣篮，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>转身勾手擦板投篮不中': [std['_0pts']],
    '<player_name>接到<player_name>的助攻，勾手命中': [std['_2pts'], std['ast']],
    '<player_name>持球翻腕违例': [std['to']],
    '<player_name>急停跳投，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>抢到前场篮板，补篮不中': [std['o_reb'] + std['_0pts']],
    '恶意犯规罚球，<player_name>罚球命中 (两罚第二罚)': [std['_1pts']],
    '<player_name>和<player_name>被吹双方犯规': [std['fol'], std['fol']],
    '<player_name><location>抛投三分入网': [std['_3pts']],
    '<player_name>接到<player_name>的助攻，<location>后仰跳投三分入网': [std['_2pts'], std['ast']],
    '<player_name><location>转身跳投打板入网': [std['_2pts']],
    '<player_name>突破反手上篮，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>急停打板跳投不中': [std['_0pts']],
    '<player_name><location>勾手，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>接到<player_name>的助攻运球突破，打板入网': [std['_2pts'], std['ast']],
    '<player_name>投篮不中': [std['_0pts']],
    '<player_name>突破打板跳投不中': [std['_0pts']],
    '<player_name>反手上篮，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name><location>三分急停跳投不中': [std['_0pts']],
    '<player_name>跑动中接到<player_name>的助攻，挑篮命中': [std['_2pts'], std['ast']],
    '<player_name>转身勾手不中': [std['_0pts']],
    '<player_name>转身后仰跳投，打板入网': [std['_2pts']],
    '<player_name>接到<player_name>的助攻运球突破，<location>打板入网': [std['_2pts'], std['ast']],
    '<player_name>二级恶意犯规 (<player_name>造成了犯规)': [std['t'], std['_0pts']],
    '<player_name>发界外球违例': [std['to']],
    '<player_name>接到<player_name>的助攻，运球突破勾手投篮得分': [std['_2pts'], std['ast']],
    '<player_name>个人犯规 (<player_name>造成了犯规)': [std['fol'], std['_0pts']],
    '<player_name>转身打板跳投不中': [std['_0pts']],
    '<player_name><location>跨步勾手命中': [std['_2pts']],
    '<player_name>助攻<player_name>，后撤步跳投<location>命中': [std['ast'], std['_2pts']],
    '<player_name>勾手命中': [std['_2pts']],
    '<player_name>出现失误': [std['fol']],
    '<player_name>加罚命中': [std['_1pts']],
    '<player_name><location>后仰跳投打板入网': [std['_2pts']],
    '<player_name>挑篮命中': [std['_2pts']],
    '<player_name><location>三分跳投不中': [std['_0pts']],
    '<player_name>打板入网': [std['_2pts']],
    '<player_name>空中接力上篮不中': [std['_0pts']],
    '<player_name>接到<player_name>的助攻，转身勾手命中': [std['_2pts'], std['ast']],
    '<player_name>带球突破反手上篮得分': [std['_2pts']],
    '<player_name>控球失误，被<player_name>断下': [std['to'], std['stl']],
    '<player_name>无球犯规 (<player_name>造成了犯规)': [std['fol'], std['_0pts']],
    '<player_name>接到<player_name>的助攻，转身后仰跳投，<location>打板入网': [std['_2pts'], std['ast']],
    '<player_name>被驱逐出场': ['_0pts'],
    '<player_name>接到<player_name>的助攻，带球突破灌篮得分': [std['_2pts'], std['ast']],
    '<player_name>突破跳投不中': [std['_0pts']],
    '<player_name><location>勾手不中': [std['_0pts']],
    '<player_name>两次运球失误': [std['to']],
    '<player_name>接到<player_name>的助攻，<location>后仰跳投命中': [std['_2pts'], std['ast']],
    '<player_name>接到<player_name>的助攻，<location>三分打板入网': [std['_2pts'], std['ast']],
    '<player_name>助攻<player_name>反手上篮得分': [std['ast'], std['_2pts']],
    '<player_name>运球突破，<location>勾手打板入网': [std['_2pts']],
    '<player_name>和<player_name>跳球，<player_name>得到篮球': [std['_0pts'], std['_0pts'], std['_0pts']],
    '<player_name><location>打板投篮，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>带球上篮不中': [std['_0pts']],
    '<player_name>急停跳投打板入网': [std['_2pts']],
    '<player_name>接到<player_name>的助攻，<location>勾手命中': [std['_2pts'], std['ast']],
    '<player_name>接到<player_name>的助攻，<location>勾手擦板入网': [std['_2pts'], std['ast']],
    '<player_name><location>急停跳投不中': [std['_0pts']],
    '<player_name><location>转身勾手命中': [std['_2pts']],
    '<player_name>带球突破灌篮得分': [std['_2pts']],
    '<player_name>无球犯规': [std['fol']],
    '<player_name><location>急停跳投打板入网': [std['_2pts']],
    '<player_name><location>转身打板跳投不中': [std['_0pts']],
    '<player_name>的失误，非法掩护': [std['to']],
    '<player_name>接到<player_name>的助攻，转身后仰跳投，打板入网': [std['_2pts'], std['ast']],
    '<player_name>踢球违例': [std['to']],
    '<player_name><location>打板投篮不中': [std['_0pts']],
    '<player_name><location>三分打板投篮不中': [std['_0pts']],
    '<player_name>后仰跳投，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name><location>三分后仰跳投不中': [std['_0pts']],
    '<player_name>防守干扰球违例': [std['to']],
    '<player_name>转身后仰跳投，<location>三分打板入网': [std['_3pts']],
    '<player_name>接到<player_name>的助攻运球突破，<location>勾手打板入网': [std['_2pts'], std['ast']],
    '<player_name>罚球争抢违例': [std['to']],
    '<player_name>助攻<player_name>，抛投命中': [std['ast'], std['_2pts']],
    '<player_name>和<player_name>跳球': [std['_0pts'], std['_0pts']],
    '<player_name>罚球不中 (两罚第二罚)': [std['_0pts']],
    '<player_name>抢到前场篮板': [std['o_reb']],
    '<player_name>接到<player_name>的助攻，<location>跳投命中': [std['_2pts'], std['ast']],
    '快攻无防守犯规罚球，<player_name>罚球不中 (两罚第二罚)': [std['_0pts']],
    '<player_name>带球上篮，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name><location>转身后仰打板跳投三分不中': [std['_0pts']],
    '快攻无防守犯规罚球，<player_name>罚球命中 (两罚第一罚)': [std['_1pts']],
    '<player_name><location>转身跳投不中': [std['_0pts']],
    '<player_name>控球失误': [std['to']],
    '<player_name><location>转身后仰打板跳投不中': [std['_0pts']],
    '<player_name><location>转身勾手不中': [std['_0pts']],
    '<player_name>助攻<player_name>挑篮命中': [std['ast'], std['_2pts']],
    '<player_name>带球突破后挑篮命中': [std['_2pts']],
    '<player_name>助攻<player_name><location>跳投三分入网': [std['ast'], std['_3pts']],
    '<player_name>灌篮，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>造成<player_name>的失误': [std['_0pts'], std['to']],
    '<player_name>接到<player_name>的助攻，带球突破反手上篮得分': [std['_2pts'], std['ast']],
    '<player_name>提前进线违例': [std['to']],
    '<player_name>勾手，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name><location>三分跳投，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>上篮不中': [std['_0pts']],
    '<player_name>罚球命中 (三罚第一罚)': [std['_1pts']],
    '<player_name>助攻<player_name>灌篮得分': [std['ast'], std['_2pts']],
    '<player_name>接到<player_name>的助攻，跨步勾手命中': [std['_2pts'], std['ast']],
    '<player_name>接到<player_name>的助攻，<location>急停跳投打板入网': [std['_2pts'], std['ast']],
    '<player_name>转身后仰跳投，<location>打板入网': [std['_2pts']],
    '<player_name><location>转身勾手擦板投篮不中': [std['_0pts']],
    '<player_name><location>三分后撤步跳投，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name><location>勾手擦板入网': [std['_2pts']],
    '<player_name>带球突破擦板勾手投篮，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>反手上篮不中': [std['_0pts']],
    '<player_name><location>跳投，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>和<team_name>队被吹双方技术犯规': [std['t']],
    '<player_name>罚球不中 (三罚第一罚)': [std['_0pts']],
    '<player_name><location>抛投，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>进攻干扰球违例': [std['to']],
    '<player_name>接到<player_name>的助攻，<location>急停跳投三分打板入网': [std['_3pts'], std['ast']],
    '<player_name>反手上篮得分': [std['_2pts']],
    '<player_name>抛投，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>防守3秒违例': [std['to']],
    '<player_name>助攻<player_name>，<location>抛投三分入网': [std['ast'], std['_3pts']],
    '<player_name>罚球不中 (三罚第二罚)': [std['_0pts']],
    '<player_name>后仰跳投不中': [std['_0pts']],
    '<player_name>罚球命中 (两罚第二罚)': [std['_1pts']],
    '<player_name>后撤步跳投不中': [std['_0pts']],
    '<player_name>跨步上篮，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>跳球违例': [std['to']],
    '<player_name>抛投命中': [std['_2pts']],
    '<player_name>罚球不中 (三罚第三罚)': [std['_0pts']],
    '<player_name>被裁判吹技术犯规': [std['t']],
    '<player_name>接到<player_name>的助攻，后仰跳投打板入网': [std['_2pts'], std['ast']],
    '<player_name>跨步扣篮得分': [std['_2pts']],
    '<player_name>接到<player_name>的助攻，打板入网': [std['_2pts'], std['ast']],
    '<player_name>一级恶意犯规 (<player_name>造成了犯规)': [std['t'], std['_0pts']],
    '恶意犯规罚球，<player_name>罚球不中 (两罚第一罚)': [std['_0pts']],
    '<player_name>助攻<player_name>命中得分': [std['ast'], std['_2pts']],
    '<player_name>接到<player_name>的助攻，勾手擦板入网': [std['_2pts'], std['ast']],
    '<player_name>传球失误，球出界': [std['to']],
    '<player_name>接到<player_name>的助攻，<location>后仰跳投打板入网': [std['_2pts'], std['ast']],
    '<player_name>罚球命中 (三罚第二罚)': [std['_1pts']],
    '<player_name>跨步反手上篮不中': [std['_0pts']],
    '<player_name>回场失误': [std['to']],
    '<player_name>运球突破低手上篮得分': [std['_2pts']],
    '<player_name>转身跳投，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name><location>三分后仰跳投，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>接到<player_name>的助攻，带球上篮得分': [std['_2pts'], std['ast']],
    '技术犯规罚球，<player_name>罚球不中': [std['_0pts']],
    '<player_name>助攻<player_name>，急停跳投命中': [std['ast'], std['_2pts']],
    '<player_name>运球突破，<location>打板入网': [std['_2pts']],
    '<player_name>运球突破，勾手打板入网': [std['_2pts']],
    '<player_name>接到<player_name>的助攻，跳投命中': [std['_2pts'], std['ast']],
    '<player_name><location>后仰跳投三分入网': [std['_3pts']],
    '<player_name>突破跳投命中': [std['_2pts']],
    '<player_name><location>后仰跳投命中': [std['_2pts']],
    '<player_name><location>转身勾手，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>跳投，被<player_name>盖掉': [std['_0pts'], std['blk']],
    '<player_name>犯规 (<player_name>造成了犯规)': [std['fol'], std['_0pts']],
    '<player_name>灌篮得分': [std['_2pts']],
    '<player_name>技术犯规': [std['t']],
    '<player_name>控球失误，球出界': [std['to']],
    '<player_name>后撤步跳投命中': [std['_2pts']],
    '<player_name><location>后仰打板跳投不中': [std['_0pts']],
    '<player_name>接到<player_name>的助攻，<location>转身跳投打板入网': [std['_2pts'], std['ast']],
    '<player_name><location>突破跳投命中': [std['_2pts']],
    '恶意犯规罚球，<player_name>罚球命中': [std['_1pts']],
    '<player_name>带球突破挑篮，被<player_name>盖掉': [std['_0pts'], std['blk']],
}
